using Broker.Backoffice.Domain.Countries;
using Microsoft.EntityFrameworkCore;

namespace Broker.Backoffice.Infrastructure.Persistence;

public static class SeedCountries
{
    public static async Task SeedAsync(AppDbContext db)
    {
        var existing = await db.Countries.ToDictionaryAsync(c => c.Iso2);
        foreach (var (iso2, iso3, name) in AllCountries)
        {
            var flag = Iso2ToFlagEmoji(iso2);
            if (existing.TryGetValue(iso2, out var country))
            {
                if (country.Name != name || country.Iso3 != iso3 || country.FlagEmoji != flag)
                {
                    country.Name = name;
                    country.Iso3 = iso3;
                    country.FlagEmoji = flag;
                }
            }
            else
            {
                db.Countries.Add(new Country
                {
                    Id = Guid.NewGuid(),
                    Iso2 = iso2,
                    Iso3 = iso3,
                    Name = name,
                    FlagEmoji = flag,
                    IsActive = true
                });
            }
        }
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Converts ISO 3166-1 alpha-2 code to Regional Indicator Symbol emoji flag.
    /// "US" → 🇺🇸, "DE" → 🇩🇪
    /// </summary>
    private static string Iso2ToFlagEmoji(string iso2)
    {
        if (iso2.Length != 2) return "";
        // Regional Indicator Symbol Letter A = U+1F1E6, 'A' = 0x41
        var first = char.ConvertFromUtf32(0x1F1E6 + (char.ToUpperInvariant(iso2[0]) - 'A'));
        var second = char.ConvertFromUtf32(0x1F1E6 + (char.ToUpperInvariant(iso2[1]) - 'A'));
        return first + second;
    }

    private static readonly (string Iso2, string Iso3, string Name)[] AllCountries =
    [
        ("AF", "AFG", "Afghanistan"),
        ("AL", "ALB", "Albania"),
        ("DZ", "DZA", "Algeria"),
        ("AS", "ASM", "American Samoa"),
        ("AD", "AND", "Andorra"),
        ("AO", "AGO", "Angola"),
        ("AG", "ATG", "Antigua and Barbuda"),
        ("AR", "ARG", "Argentina"),
        ("AM", "ARM", "Armenia"),
        ("AU", "AUS", "Australia"),
        ("AT", "AUT", "Austria"),
        ("AZ", "AZE", "Azerbaijan"),
        ("BS", "BHS", "Bahamas"),
        ("BH", "BHR", "Bahrain"),
        ("BD", "BGD", "Bangladesh"),
        ("BB", "BRB", "Barbados"),
        ("BY", "BLR", "Belarus"),
        ("BE", "BEL", "Belgium"),
        ("BZ", "BLZ", "Belize"),
        ("BJ", "BEN", "Benin"),
        ("BM", "BMU", "Bermuda"),
        ("BT", "BTN", "Bhutan"),
        ("BO", "BOL", "Bolivia"),
        ("BA", "BIH", "Bosnia and Herzegovina"),
        ("BW", "BWA", "Botswana"),
        ("BR", "BRA", "Brazil"),
        ("BN", "BRN", "Brunei"),
        ("BG", "BGR", "Bulgaria"),
        ("BF", "BFA", "Burkina Faso"),
        ("BI", "BDI", "Burundi"),
        ("CV", "CPV", "Cabo Verde"),
        ("KH", "KHM", "Cambodia"),
        ("CM", "CMR", "Cameroon"),
        ("CA", "CAN", "Canada"),
        ("KY", "CYM", "Cayman Islands"),
        ("CF", "CAF", "Central African Republic"),
        ("TD", "TCD", "Chad"),
        ("CL", "CHL", "Chile"),
        ("CN", "CHN", "China"),
        ("CO", "COL", "Colombia"),
        ("KM", "COM", "Comoros"),
        ("CG", "COG", "Congo"),
        ("CD", "COD", "Congo (DRC)"),
        ("CR", "CRI", "Costa Rica"),
        ("CI", "CIV", "Cote d'Ivoire"),
        ("HR", "HRV", "Croatia"),
        ("CU", "CUB", "Cuba"),
        ("CW", "CUW", "Curacao"),
        ("CY", "CYP", "Cyprus"),
        ("CZ", "CZE", "Czechia"),
        ("DK", "DNK", "Denmark"),
        ("DJ", "DJI", "Djibouti"),
        ("DM", "DMA", "Dominica"),
        ("DO", "DOM", "Dominican Republic"),
        ("EC", "ECU", "Ecuador"),
        ("EG", "EGY", "Egypt"),
        ("SV", "SLV", "El Salvador"),
        ("GQ", "GNQ", "Equatorial Guinea"),
        ("ER", "ERI", "Eritrea"),
        ("EE", "EST", "Estonia"),
        ("SZ", "SWZ", "Eswatini"),
        ("ET", "ETH", "Ethiopia"),
        ("FJ", "FJI", "Fiji"),
        ("FI", "FIN", "Finland"),
        ("FR", "FRA", "France"),
        ("GA", "GAB", "Gabon"),
        ("GM", "GMB", "Gambia"),
        ("GE", "GEO", "Georgia"),
        ("DE", "DEU", "Germany"),
        ("GH", "GHA", "Ghana"),
        ("GI", "GIB", "Gibraltar"),
        ("GR", "GRC", "Greece"),
        ("GL", "GRL", "Greenland"),
        ("GD", "GRD", "Grenada"),
        ("GU", "GUM", "Guam"),
        ("GT", "GTM", "Guatemala"),
        ("GG", "GGY", "Guernsey"),
        ("GN", "GIN", "Guinea"),
        ("GW", "GNB", "Guinea-Bissau"),
        ("GY", "GUY", "Guyana"),
        ("HT", "HTI", "Haiti"),
        ("HN", "HND", "Honduras"),
        ("HK", "HKG", "Hong Kong"),
        ("HU", "HUN", "Hungary"),
        ("IS", "ISL", "Iceland"),
        ("IN", "IND", "India"),
        ("ID", "IDN", "Indonesia"),
        ("IR", "IRN", "Iran"),
        ("IQ", "IRQ", "Iraq"),
        ("IE", "IRL", "Ireland"),
        ("IM", "IMN", "Isle of Man"),
        ("IL", "ISR", "Israel"),
        ("IT", "ITA", "Italy"),
        ("JM", "JAM", "Jamaica"),
        ("JP", "JPN", "Japan"),
        ("JE", "JEY", "Jersey"),
        ("JO", "JOR", "Jordan"),
        ("KZ", "KAZ", "Kazakhstan"),
        ("KE", "KEN", "Kenya"),
        ("KI", "KIR", "Kiribati"),
        ("KP", "PRK", "North Korea"),
        ("KR", "KOR", "South Korea"),
        ("KW", "KWT", "Kuwait"),
        ("KG", "KGZ", "Kyrgyzstan"),
        ("LA", "LAO", "Laos"),
        ("LV", "LVA", "Latvia"),
        ("LB", "LBN", "Lebanon"),
        ("LS", "LSO", "Lesotho"),
        ("LR", "LBR", "Liberia"),
        ("LY", "LBY", "Libya"),
        ("LI", "LIE", "Liechtenstein"),
        ("LT", "LTU", "Lithuania"),
        ("LU", "LUX", "Luxembourg"),
        ("MO", "MAC", "Macao"),
        ("MG", "MDG", "Madagascar"),
        ("MW", "MWI", "Malawi"),
        ("MY", "MYS", "Malaysia"),
        ("MV", "MDV", "Maldives"),
        ("ML", "MLI", "Mali"),
        ("MT", "MLT", "Malta"),
        ("MH", "MHL", "Marshall Islands"),
        ("MR", "MRT", "Mauritania"),
        ("MU", "MUS", "Mauritius"),
        ("MX", "MEX", "Mexico"),
        ("FM", "FSM", "Micronesia"),
        ("MD", "MDA", "Moldova"),
        ("MC", "MCO", "Monaco"),
        ("MN", "MNG", "Mongolia"),
        ("ME", "MNE", "Montenegro"),
        ("MA", "MAR", "Morocco"),
        ("MZ", "MOZ", "Mozambique"),
        ("MM", "MMR", "Myanmar"),
        ("NA", "NAM", "Namibia"),
        ("NR", "NRU", "Nauru"),
        ("NP", "NPL", "Nepal"),
        ("NL", "NLD", "Netherlands"),
        ("NZ", "NZL", "New Zealand"),
        ("NI", "NIC", "Nicaragua"),
        ("NE", "NER", "Niger"),
        ("NG", "NGA", "Nigeria"),
        ("MK", "MKD", "North Macedonia"),
        ("NO", "NOR", "Norway"),
        ("OM", "OMN", "Oman"),
        ("PK", "PAK", "Pakistan"),
        ("PW", "PLW", "Palau"),
        ("PS", "PSE", "Palestine"),
        ("PA", "PAN", "Panama"),
        ("PG", "PNG", "Papua New Guinea"),
        ("PY", "PRY", "Paraguay"),
        ("PE", "PER", "Peru"),
        ("PH", "PHL", "Philippines"),
        ("PL", "POL", "Poland"),
        ("PT", "PRT", "Portugal"),
        ("PR", "PRI", "Puerto Rico"),
        ("QA", "QAT", "Qatar"),
        ("RO", "ROU", "Romania"),
        ("RU", "RUS", "Russia"),
        ("RW", "RWA", "Rwanda"),
        ("KN", "KNA", "Saint Kitts and Nevis"),
        ("LC", "LCA", "Saint Lucia"),
        ("VC", "VCT", "Saint Vincent and the Grenadines"),
        ("WS", "WSM", "Samoa"),
        ("SM", "SMR", "San Marino"),
        ("ST", "STP", "Sao Tome and Principe"),
        ("SA", "SAU", "Saudi Arabia"),
        ("SN", "SEN", "Senegal"),
        ("RS", "SRB", "Serbia"),
        ("SC", "SYC", "Seychelles"),
        ("SL", "SLE", "Sierra Leone"),
        ("SG", "SGP", "Singapore"),
        ("SX", "SXM", "Sint Maarten"),
        ("SK", "SVK", "Slovakia"),
        ("SI", "SVN", "Slovenia"),
        ("SB", "SLB", "Solomon Islands"),
        ("SO", "SOM", "Somalia"),
        ("ZA", "ZAF", "South Africa"),
        ("SS", "SSD", "South Sudan"),
        ("ES", "ESP", "Spain"),
        ("LK", "LKA", "Sri Lanka"),
        ("SD", "SDN", "Sudan"),
        ("SR", "SUR", "Suriname"),
        ("SE", "SWE", "Sweden"),
        ("CH", "CHE", "Switzerland"),
        ("SY", "SYR", "Syria"),
        ("TW", "TWN", "Taiwan"),
        ("TJ", "TJK", "Tajikistan"),
        ("TZ", "TZA", "Tanzania"),
        ("TH", "THA", "Thailand"),
        ("TL", "TLS", "Timor-Leste"),
        ("TG", "TGO", "Togo"),
        ("TO", "TON", "Tonga"),
        ("TT", "TTO", "Trinidad and Tobago"),
        ("TN", "TUN", "Tunisia"),
        ("TR", "TUR", "Turkey"),
        ("TM", "TKM", "Turkmenistan"),
        ("TV", "TUV", "Tuvalu"),
        ("UG", "UGA", "Uganda"),
        ("UA", "UKR", "Ukraine"),
        ("AE", "ARE", "United Arab Emirates"),
        ("GB", "GBR", "United Kingdom"),
        ("US", "USA", "United States"),
        ("UY", "URY", "Uruguay"),
        ("UZ", "UZB", "Uzbekistan"),
        ("VU", "VUT", "Vanuatu"),
        ("VA", "VAT", "Vatican City"),
        ("VE", "VEN", "Venezuela"),
        ("VN", "VNM", "Vietnam"),
        ("VG", "VGB", "British Virgin Islands"),
        ("VI", "VIR", "U.S. Virgin Islands"),
        ("YE", "YEM", "Yemen"),
        ("ZM", "ZMB", "Zambia"),
        ("ZW", "ZWE", "Zimbabwe"),
        ("AW", "ABW", "Aruba"),
        ("AX", "ALA", "Aland Islands"),
        ("BL", "BLM", "Saint Barthelemy"),
        ("BQ", "BES", "Bonaire"),
        ("CC", "CCK", "Cocos Islands"),
        ("CK", "COK", "Cook Islands"),
        ("FO", "FRO", "Faroe Islands"),
        ("GF", "GUF", "French Guiana"),
        ("PF", "PYF", "French Polynesia"),
        ("GP", "GLP", "Guadeloupe"),
        ("MF", "MAF", "Saint Martin"),
        ("MQ", "MTQ", "Martinique"),
        ("MS", "MSR", "Montserrat"),
        ("NC", "NCL", "New Caledonia"),
        ("NU", "NIU", "Niue"),
        ("NF", "NFK", "Norfolk Island"),
        ("MP", "MNP", "Northern Mariana Islands"),
        ("RE", "REU", "Reunion"),
        ("PM", "SPM", "Saint Pierre and Miquelon"),
        ("SH", "SHN", "Saint Helena"),
        ("TC", "TCA", "Turks and Caicos Islands"),
        ("TK", "TKL", "Tokelau"),
        ("WF", "WLF", "Wallis and Futuna"),
        ("YT", "MYT", "Mayotte"),
        ("EH", "ESH", "Western Sahara"),
        ("IO", "IOT", "British Indian Ocean Territory"),
        ("CX", "CXR", "Christmas Island"),
        ("FK", "FLK", "Falkland Islands"),
        ("TF", "ATF", "French Southern Territories"),
        ("HM", "HMD", "Heard Island and McDonald Islands"),
        ("PN", "PCN", "Pitcairn Islands"),
        ("GS", "SGS", "South Georgia"),
        ("SJ", "SJM", "Svalbard and Jan Mayen"),
        ("UM", "UMI", "U.S. Minor Outlying Islands"),
        ("AI", "AIA", "Anguilla"),
        ("AQ", "ATA", "Antarctica"),
        ("BV", "BVT", "Bouvet Island"),
        ("XK", "XKX", "Kosovo"),
    ];
}
