using Broker.Backoffice.Domain.Instruments;

namespace Broker.Backoffice.Application.Instruments;

public sealed record InstrumentDto(
    Guid Id,
    string Symbol,
    string Name,
    string? ISIN,
    string? CUSIP,
    InstrumentType Type,
    AssetClass AssetClass,
    InstrumentStatus Status,
    Guid? ExchangeId,
    string? ExchangeCode,
    string? ExchangeName,
    Guid? CurrencyId,
    string? CurrencyCode,
    Guid? CountryId,
    string? CountryName,
    string? CountryFlagEmoji,
    Sector? Sector,
    int LotSize,
    decimal? TickSize,
    decimal? MarginRequirement,
    bool IsMarginEligible,
    DateTime? ListingDate,
    DateTime? DelistingDate,
    DateTime? ExpirationDate,
    string? IssuerName,
    string? Description,
    string? ExternalId,
    DateTime CreatedAt,
    byte[] RowVersion);

public sealed record InstrumentListItemDto(
    Guid Id,
    string Symbol,
    string Name,
    string? ISIN,
    string? CUSIP,
    InstrumentType Type,
    AssetClass AssetClass,
    InstrumentStatus Status,
    string? ExchangeCode,
    string? ExchangeName,
    string? CurrencyCode,
    string? CountryName,
    string? CountryFlagEmoji,
    Sector? Sector,
    int LotSize,
    bool IsMarginEligible,
    string? ExternalId,
    DateTime CreatedAt,
    byte[] RowVersion);
